### PR TITLE
Remove UMD & CJS builds

### PR DESCRIPTION
**Pull request by manzt**
Fixes failing build in: https://github.com/hms-dbmi/viv/pull/483

When we create a tagged release (tarball), the repo doesn't contain the `dist-node` or `dist-browser`, so the package is "broken" because the `"main"` entrypoint is missing. This causes issues with module resolution for tools like `eslint` and other tooling (like VSCode intellisense).

This is happening because a dependency that is a git _branch_ will run the `npm prepare` script on install,

```
"geotiff": "ilan-gold/geotiff.js#viv",
```

but a tarball is just unpacked as static assets

```
"geotiff": "https://github.com/ilan-gold/geotiff.js/archive/refs/tags/viv-0.0.1.tar.gz"
```

Bundlers don't use the UMD or CJS builds of this project. UMD is an outdated format, and CJS can only run on the server. The easiest solution is to just avoid creating these outputs.

This is preferable IMO because 1.) A tarball is what you install from `npm` normally, and 2.) installing geotiff for viv-based projects should not need the commonjs or UMD bundles. By removing these builds, we can continue to create tagged releases of just the `geotiff.js` (rather than creating additional branches).

### CODE REVIEW

**Comment by ilan-gold** [comment]
@manzt Why not just use `ilan-gold/geotiff.js#viv-0.0.1`?  I think this does the release tag.
> 1.) A tarball is what you install from npm normally

But the tarball doesn't contain `dist`?  Wouldn't the npm install contain the built `dist`?

**Comment by manzt** [comment]
> @manzt Why not just use `ilan-gold/geotiff.js#viv-0.0.1`? I think this does the release tag.

This should work, yes.

> But the tarball doesn't contain `dist`? Wouldn't the npm install contain the built `dist`?

Correct, this tarball doesn't contain `dist-*` directories, but they aren't required for bundlers/browsers. This PR was to suggest removing these assets from the `package.json` to simplify install. By using our _branch_ for geotiff (not the tagged tarball), when someone installs viv they need to 1.) install both geotiff's `dependencies` _and_ `devDependencies` and 2.) to build geotiff from source (run `parcel`).

The second point is what causes issues on windows and could be avoided all together.

**Comment by ilan-gold** [comment]
Ok so you're proposing?
1. Merge this change
2. Make a new release
3. Update https://github.com/hms-dbmi/viv/pull/483 which should make it work with the tarball?
4. (Also add this change to the Viv PR: https://github.com/hms-dbmi/viv/pull/484/files#diff-08ce86acb97df5f56e5d0e56d6f70082ce11e987bebc0651834874045278e8d6R35-R38)

**Comment by manzt** [comment]
Yup! 

5.) Update `rollup.config.test.js`:

```diff
diff --git a/rollup.config.test.js b/rollup.config.test.js
index 0c4d12d..c5f6277 100644
--- a/rollup.config.test.js
+++ b/rollup.config.test.js
@@ -6,10 +6,8 @@ export default {
   output: {
     format: 'cjs'
   },
-  // All non-relative paths are external
-  external: [/^[^.\/]|^\.[^.\/]|^\.\.[^\/]/],
   plugins: [
-    resolve(),
+    resolve({ resolveOnly: ['geotiff'] }),
     glslify(),
     sucrase({ transforms: ['jsx', 'typescript'] })
   ]
```

**Comment by ilan-gold** [comment]
Ok!

**Pull request merged**
